# Generated by Django 4.0.6 on 2022-07-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf2word_conv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='upload',
            new_name='file',
        ),
    ]
