# Generated by Django 4.0.6 on 2022-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf2word_conv', '0002_rename_upload_uploaded_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_file',
            name='file',
            field=models.FileField(upload_to='pdf2word_conv/uploads/'),
        ),
    ]
