# Generated by Django 4.0.6 on 2022-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf2word_conv', '0003_alter_uploaded_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
